// counterSaga
const ADDONE = 'ADDONE';
const SUBTRACTONE = 'SUBTRACTONE';
const ADDBYAMOUNT = 'ADDBYAMOUNT';
const RANDOMCOMPUTATION = 'RANDOMCOMPUTATION';

// testApiSaga
const TESTAPIFETCH = 'TESTAPIFETCH';

// modalControlSaga
const MODALCONTROL = 'MODALCONTROL';

// authSaga
const AUTH_SETTING = 'AUTH_SETTING';
const AUTH_RESET = 'AUTH_RESET';
const AUTH_SETTING_BY_TOKEN = 'AUTH_SETTING_BY_TOKEN';

// registerSaga
const REGISTER_STEP_ONE = 'REGISTER_STEP_ONE';
const ID_CHECK = 'ID_CHECK';
const TEAM_LIST = 'TEAM_LIST';
const VALID_STEP1 = 'VALID_STEP1';
const VALID_STEP2 = 'VALID_STEP2';
const VALID_STEP3 = 'VALID_STEP3';
const REGISTER_USER = 'REGISTER_USER';
const SEND_USER_IMG = 'SEND_USER_IMG';

export {
	ADDONE,
	SUBTRACTONE,
	ADDBYAMOUNT,
	RANDOMCOMPUTATION,
	TESTAPIFETCH,
	MODALCONTROL,
	AUTH_SETTING,
	AUTH_RESET,
	ID_CHECK,
	REGISTER_STEP_ONE,
	TEAM_LIST,
	VALID_STEP1,
	VALID_STEP2,
	VALID_STEP3,
	REGISTER_USER,
	SEND_USER_IMG,
	AUTH_SETTING_BY_TOKEN,
};
