// counterSaga
const ADDONE = 'ADDONE';
const SUBTRACTONE = 'SUBTRACTONE';
const ADDBYAMOUNT = 'ADDBYAMOUNT';
const RANDOMCOMPUTATION = 'RANDOMCOMPUTATION';

// testApiSaga
const TESTAPIFETCH = 'TESTAPIFETCH';

// modalControlSaga
const MODALCONTROL = 'MODALCONTROL';

export { ADDONE, SUBTRACTONE, ADDBYAMOUNT, RANDOMCOMPUTATION, TESTAPIFETCH, MODALCONTROL };
